---
title: "Tour de France"
author: "Wenjun"
date: "2020/4/7"
output: 
  html_document:
    df_print: paged
    code_folding: show
    fig_width: 8
    fig_height: 6
---

```{r Setup, include=FALSE, results='hide', warning=FALSE}
library(knitr)
opts_chunk$set(fig.path="figures\\",
               cache.path="cache\\",
               cache=FALSE,
               echo=TRUE,
               message=FALSE,
               warning=FALSE) 
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(dplyr)
library(lubridate)
```

# Tour de France {.tabset .tabset-fade}

## Data

```{r get the data, results='hide'}
library(tidytuesdayR)
tuesdata <- tidytuesdayR::tt_load('2020-04-07')
tdf_stages <- tuesdata$tdf_stages
```


```{r}
library(lubridate)

#unique(tolower(tdf_stages$Type))
stage <- tdf_stages %>%
  mutate(year = year(ymd(Date))) %>%
  mutate(Type = tolower(Type)) %>%
  mutate(Type = case_when(Type %in% c("flat stage", "flat cobblestone stage", "plain stage", "plain stage with cobblestones") ~ "Flat", 
                          Type %in% c("medium mountain stage", "high mountain stage", "mountain stage", "hilly stage", "stage with mountain(s)", "stage with mountain", "mountain time trial") ~ "Mountain", 
                          TRUE ~ "Other")) %>%
  filter(Type %in% c("Mountain", "Flat")) %>%
  group_by(year, Type) %>%
  summarise(sumDistance = sum(Distance)) %>%
  mutate(percentage = sumDistance/sum(sumDistance))
```

## Plot

```{r plot proportion}
stage$Type <- factor(stage$Type, levels = c("Flat", "Mountain"))

ggplot(stage, 
       aes(x=year, y=percentage, fill = Type)) +
  geom_area(size=1.5, color="white") + 
  geom_text(data = stage %>% filter(year == 2017 & Type == "Mountain"), 
            aes(label = paste0("Mountain\nRate ",round(percentage*100,0),"%"), 
                fontface = "bold", 
                hjust = -0.1, 
                lineheight = 0.9)) + 
  geom_point(data = stage %>% filter(year == 2017 & Type == "Mountain"), 
             shape = 21, size = 3, stroke = 2, color = "white", fill = "black") + 
  
  
  scale_x_continuous(breaks = c(1903, 1920, 1940, 1960, 1980, 2000, 2017), expand=expansion(0.13,0)) + 
  scale_y_continuous(expand = c(0, 0)) +
  scale_fill_manual(values=c("#d9bf77", "#2b580c")) + 

  
  labs(
    title = "An Increasing Proportion of Tour De France is on Mountain Stages", 
    subtitle = "Percentage of distance covered on mountain stages and flat stages (when only consider mountain and flat stages)", 
    caption = paste(c("Source: Package 'tdf', developed by Alastair Rushworth",
                     "#TidyTuesday 2020W15",
                     "@Wenjun_SUN_",
                     "github.com/SUN-Wenjun"),
                     collapse = "\n")  
  ) + 
  
  theme_hc() + 
  
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.major.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    legend.position = "top",
    legend.title = element_blank(),
    plot.subtitle=element_text(size=10, color="grey60", face="italic"),
    plot.caption=element_text(size=8, color="grey60")
  )
```

```{r plot distance}
ggplot(stage, 
       aes(x=year, y=sumDistance, fill = Type)) +
  geom_area(alpha = 0.8) + 
  
  scale_fill_manual(values=c("#d9bf77", "#2b580c")) + 
  scale_x_continuous(breaks = c(1903, 1920, 1940, 1960, 1980, 2000, 2017)) +
  scale_y_continuous(expand = c(0, 0)) +
  
  labs(title = "Distances covers on mountain stages and flat stages") + 
  ylab("Distance (km)") + 
  
  theme_hc() + 
  
  theme(
    axis.title.x = element_blank(),
    legend.position = "top",
    legend.title = element_blank()
  )
```

```{r plot include other types of stage}
stage2 <- tdf_stages %>%
  mutate(year = year(ymd(Date))) %>%
  mutate(Type = tolower(Type)) %>%
  mutate(Type = case_when(Type %in% c("flat stage", "flat cobblestone stage", "plain stage", "plain stage with cobblestones") ~ "Flat", 
                          Type %in% c("medium mountain stage", "high mountain stage", "mountain stage", "hilly stage", "stage with mountain(s)", "stage with mountain", "mountain time trial") ~ "Mountain", 
                          TRUE ~ "Other")) %>%
  group_by(year, Type) %>%
  summarise(sumDistance = sum(Distance)) %>%
  mutate(percentage = sumDistance/sum(sumDistance))


ggplot(stage2, aes(x=year, y=sumDistance, fill = Type)) +
geom_area() + 

scale_fill_manual(values=c("#d9bf77", "#2b580c", "#8db1ab")) + 
scale_x_continuous(breaks = c(1903, 1920, 1927, 1940, 1960, 1980, 2000, 2017)) +
scale_y_continuous(expand = c(0, 0)) +

labs(title = "Distances covers on mountain stages, flat stages, and other stages") + 
ylab("Distance (km)") + 

theme_hc() + 

theme(
  axis.title.x = element_blank(),
  legend.position = "top",
  legend.title = element_blank()
)

```


