---
title: "TidyTuesday 2020W17"
author: "Wenjun"
date: "2020/4/21"
output: 
  html_document:
    df_print: paged
    code_folding: show
    fig_width: 8
    fig_height: 6
---

```{r Setup, include=FALSE, results='hide', warning=FALSE}
library(knitr)
opts_chunk$set(fig.path="figures\\",
               cache.path="cache\\",
               cache=FALSE,
               echo=TRUE,
               message=FALSE,
               warning=FALSE) 

library(tidyverse)
library(dplyr)
library(stringr)
library(ggplot2)
library(waffle)
library(hrbrthemes)
library(ggthemes)
library(ggtext)
```

# Keep Calm and Comply with GDPR {.tabset .tabset-fade}

## Get the data

```{r warning=FALSE}
gdpr_violations <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-21/gdpr_violations.tsv')
```

## Preprocess

```{r}
library(stringr)

gdpr_violations[str_detect(gdpr_violations$controller, "Google"),]$controller <- "Google"

google_fine <- gdpr_violations %>%
  filter(controller == "Google") %>%
  summarise(total = sum(price)/1000000*1.18) %>% # in million, in US dollar
  as.numeric()
```

Get revenue and net income from [Alphabet's 2019 Fourth Quarter and Fiscal Year Results](https://abc.xyz/investor/static/pdf/2019Q4_alphabet_earnings_release.pdf).

```{r}
google_revenue <- 161857 # in million USD
google_income <- 34343 # in million 
```


## Visualize 

```{r warning=FALSE}
library(waffle)
library(hrbrthemes)
library(ggtext)

df <- data.frame(parts = c("income", "fine"),
                 vals = c(google_income/google_fine, google_fine/google_fine))


ggplot(df, aes(fill = parts, values = vals)) +
  geom_waffle(n_rows = 45, size = 0.5, colour = "white", flip = TRUE) +
  
  scale_fill_manual(
    name = NULL,
    values = c("#DB4437", "#e6e6e6"),
    labels = c("Fine", "Income")
  ) +
  
  coord_equal() +
  
  labs(
    title = "<b><span style = 'font-size:14pt'><span style = 'color:#DB4437'>$67 Million Is A Lot, </span>But Probably Not For Google</b>",
    subtitle = "<span style = 'color:#333333'>Google is fined $67 million in total under Europe’s General Data Protection Regulation (GDPR), \nbut this is just less than <span style = 'color:#DB4437'>0.2%</span> of its net income in 2019.</span>",
    caption = "@Wenjun_SUN_\n#TidyTuesday2020W17\nSource:https://www.privacyaffairs.com/gdpr-fines/ & https://abc.xyz/investor/static/pdf/2019Q4_alphabet_earnings_release.pdf\nNote: The net income already includes a loss of $1,697 million for European Commission fines."  
    ) + 
  
  theme_ipsum_rc(grid="") +
  theme_enhance_waffle() + 
  theme(
    legend.position = "none",
    plot.caption=element_text(size=7, color="#b3b3b3"),
    plot.title = element_textbox_simple(
      lineheight = 1,
      padding = margin(5.5, 5.5, 0, 5.5),
      margin = margin(0, 0, 0, 0)),
    plot.subtitle = element_textbox_simple(
      face = "italic",
      size = 10,
      lineheight = 1,
      padding = margin(5.5, 5.5, 5.5, 5.5),
      margin = margin(0, 0, 5.5, 0))
  )
```








